baseURL = "https://huayu0824.github.io/"
languageCode = "zh-cn"
title = "我的研究博客"
theme = "PaperMod"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "文章"
        url = "/posts/"
        weight = 10
